#!/usr/bin/env ruby

require_relative '../lib/trees'

module CLI
  extend Trees

  line('say :word') do |word|
    summary { 'Talks to the user.' }
    execute { puts word }
  end

  line('build --env=:env') do |env|
    execute { puts env }
  end
end

CLI.run(ARGV)
